### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by rrosenblum**

### CODE REVIEW

**Comment by uchagani** [comment]
@rrosenblum thanks for doing this.  Can you fix the remaining errors?

**Comment by rrosenblum** [comment]
The current build errors are coming from `selenium-webdriver` 3.x not supporting Ruby 1.9.3. `selenium-webdriver` is a dependency of `watir-webdriver` which requires `selenium-webdriver >= 2.46.2`. 

The options are:
1. Forcefully cap the version of `selenium-webdriver` to less than 3.x
 - I do not recommend this because it will prevent people from getting the benefits of newer versions of `selenium-webdriver`
2. Create more Gemfiles to support more permutations. 
 - I do not recommend this either because the permutations will become difficult to maintain
3. Drop support for Ruby 1.9.3
 - Unless there is a large number of Ruby 1.9.3 projects that you know of that are using Taza, I recommend this solution because support for Ruby 1.9.3 ended last year.

**Comment by uchagani** [comment]
We're okay with dropping support for ruby 1.9.3 with this next version of taza so feel free to drop it @rrosenblum

**Comment by rrosenblum** [comment]
I'm having a bit of trouble with the builds in Travis. From what I can tell, everything is configured properly, but I am still getting build errors. I am not sure if the issue is with the configuration, or if it is an issue on Travis's side. I will keep tweaking the configuration until I find something that works.

**Comment by rrosenblum** [comment]
This is ready for reveiw/merging.

**Comment by uchagani** [comment]
awesome thanks for doing this @rrosenblum .  I'll take a look this evening.  @orieken can you get another set of eyes on this please?

**Comment by orieken** [comment]
Looks good to me 👍

**Pull request merged**
