### PR TITLE
Settings now accept erb'd files

### PR DESCRIPTION
**Pull request by drewboardman**
I've made a small change to the settings.rb file. Our site_file needs to resolve the hostname it is making requests from, so the file needed to be ERB'd. I've ensured that the old functionality remains stable:

 a) .erb file extensions are optional - so the File.join on line 26 does not throw an exception for .yml files
 b) Static YAML files are not affected by ERB.new

Additionally I've ran the default rake task, and the unit tests pass.

### CODE REVIEW

**Comment by uchagani** [comment]
@drewboardman looks like this is failing against ruby 1.9.3.  The previous build passed.  Can you take a look into the failure?

**Comment by drewboardman** [comment]
Sorry about the late reply, I was out of the office for the holidays. Are these Travis logs the only straces you have for this failure? It looks like the rake spec task isn't executing, but the exact issue is hard to determine from the logs on Travis.

I'm wondering if maybe it's because I added my ruby version files to the repo?

**Comment by drewboardman** [comment]
I've actually had the Travis build pass twice with the changes I've made. Would you mind attempting it on your end again?

https://travis-ci.org/drewboardman/taza/builds

**Comment by uchagani** [comment]
can you revert this commit please: c6ad6330797a8a39c5aa2469c64bacd5af59955e

**Pull request closed without merging**
