### PR TITLE
Added error validation logic to settings.rb for TAZA_ENV

### PR DESCRIPTION
**Pull request by lfingerman**

### CODE REVIEW

**Comment by uchagani** [comment]
The error you're getting in travis is related to the bundler.  Please modify ```travis.yml``` to this:

```yaml
before_install:
  - gem update --system
  - gem update bundler
```

**Comment by lfingerman** [comment]
looks like that change didn't help

**Comment by uchagani** [comment]
@lfingerman looks like latest rubygems is broken with ruby-head according to https://github.com/rubygems/rubygems/issues/1220

Please modify ```.travis.yml``` with the following:

```yaml
before_install: gem update --system 2.4.8
```

**Comment by uchagani** [comment]
closing this PR because it hasn't been updated in a while.  the idea here we like but we feel the implementation can be cleaner.

**Pull request closed without merging**
