### PR TITLE
Use watir instead of watir-webdriver and firewater

### PR DESCRIPTION
**Pull request by rrosenblum**
This change is needed to support Ruby 2.4+.

### CODE REVIEW

**Comment by uchagani** [comment]
@rrosenblum is this a breaking change that will required a major version bump?

**Comment by rrosenblum** [comment]
I'm not fully sure. I don't know anything much about `firewatir` and `safariwatir`. It mainly comes down to how `watir` may behave differently than `watir-webdriver`. It looks like the api to create a browser has stayed the same so not much risk there. I think it really comes down to are there any breaking changes going from `watir` 5 to 6. Testing against the project at work went fine. 

I think it would be a good idea for `Taza` to get out of the business of creating browsers are require that the user pass the browser in. That would be a breaking change that we would probably want to first deprecate.

https://github.com/watir/watir/blob/master/CHANGES.md

**Comment by uchagani** [comment]
To err on the side of caution I'd like to bump a major for this PR.  @orieken @lunks, thoughts?

**Comment by rrosenblum** [comment]
I am cool with that. @tnypxl might be able to provide some insight. I believe he has made a similar change on his fork.

**Comment by rrosenblum** [comment]
@uchagani, @orieken, and @lunks any update on this? This is preventing us from upgrading our application to Ruby 2.4.

**Comment by uchagani** [comment]
@rrosemblum can you include the major version bump as part of this PR. Then it will be ready to merge.

**Comment by rrosenblum** [comment]
@uchagani I have bumped the gem version and updated the history.

**Comment by uchagani** [comment]
merged.  Thanks!

**Comment by rrosenblum** [comment]
@uchagani can you please push the new of the gem to RubyGems?

**Comment by uchagani** [comment]
Working on it @rrosenblum.  I don't have permissions so sorting everything out.  Will update you when it's pushed.

**Comment by uchagani** [comment]
@rrosenblum v3 is pushed to rubygems.  thanks @orieken for getting this done so quickly.

**Pull request merged**
